# Generated by Django 4.2.15 on 2024-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULogin', '0019_blockfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
